### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by isieo** [Saltycustoms/kantan#1]
I don't know how secure is it running shell script directly from sinatra.
there should be a better way.

**Comment by parasquid** [comment]
How about a background worker listening for instructions from Sinatra? The BG workercan then call to the shell, which may or may not be on the same system as the Sinatra app.

**Comment by isieo** [comment]
I am trying hard not to have a background process as blogging happens only once in awhile. I wonder if I can use github hook or something.

**Comment by parasquid** [comment]
Maybe not a github webhook, but a proper git hook like https://git-scm.com/docs/githooks#post-receive ?
So the bare repo at the server would then run a jekyll build on a git push.
I guess the issue with this is finding the ruby library that can do git stuff without having to resort to the shell.

**Comment by isieo** [comment]
hm.. i think we should keep it simple and stick to running scripts, we just need to ensure its safe

**Comment by isieo** [comment]
i am closing this for now. i think the file security part is sufficient.
